// Comprehensive staple recipes - the dishes everyone should know
// These are manually curated for quality and completeness

export interface StapleRecipe {
  id: string;
  name: string;
  description: string;
  image: string;
  prepTime: number;
  cookTime: number;
  servings: number;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  cuisine: string;
  category: string;
  ingredients: { item: string; amount: string; optional?: boolean }[];
  instructions: string[];
  tags: string[];
  mealType?: string[];
}

export const stapleRecipes: StapleRecipe[] = [
  // ============ BREAKFAST STAPLES ============
  {
    id: 'staple-1',
    name: 'Classic Scrambled Eggs',
    description: 'Perfectly creamy scrambled eggs with butter, cooked low and slow for the best texture.',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800',
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Breakfast',
    ingredients: [
      { item: 'eggs', amount: '4 large' },
      { item: 'butter', amount: '2 tbsp' },
      { item: 'salt', amount: '1/4 tsp' },
      { item: 'black pepper', amount: 'to taste' },
      { item: 'chives', amount: '1 tbsp, chopped', optional: true },
    ],
    instructions: [
      'Crack eggs into a bowl and beat with a fork until yolks and whites are combined.',
      'Melt butter in a non-stick pan over medium-low heat.',
      'Add beaten eggs to the pan. Let them sit for 20 seconds until edges start to set.',
      'Using a spatula, gently push eggs from edges toward center, creating soft curds.',
      'Continue folding and pushing every 20 seconds. Remove from heat while still slightly wet.',
      'Season with salt and pepper, garnish with chives if desired. Serve immediately.',
    ],
    tags: ['breakfast', 'eggs', 'quick', 'easy', 'vegetarian'],
    mealType: ['Breakfast'],
  },
  {
    id: 'staple-2',
    name: 'Fluffy Pancakes',
    description: 'Light and fluffy homemade pancakes that are better than any mix.',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800',
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Breakfast',
    ingredients: [
      { item: 'all-purpose flour', amount: '1.5 cups' },
      { item: 'baking powder', amount: '3.5 tsp' },
      { item: 'sugar', amount: '1 tbsp' },
      { item: 'salt', amount: '1/4 tsp' },
      { item: 'milk', amount: '1.25 cups' },
      { item: 'egg', amount: '1' },
      { item: 'melted butter', amount: '3 tbsp' },
      { item: 'vanilla extract', amount: '1 tsp', optional: true },
    ],
    instructions: [
      'In a large bowl, whisk together flour, baking powder, sugar, and salt.',
      'Make a well in the center and pour in milk, egg, melted butter, and vanilla.',
      'Mix until smooth but don\'t overmix - some lumps are okay.',
      'Heat a griddle or pan over medium heat and lightly grease with butter.',
      'Pour 1/4 cup batter for each pancake.',
      'Cook until bubbles form on surface and edges look set, about 2-3 minutes.',
      'Flip and cook until golden brown, about 1-2 more minutes.',
      'Serve warm with maple syrup, butter, or fresh fruit.',
    ],
    tags: ['breakfast', 'pancakes', 'brunch', 'vegetarian'],
    mealType: ['Breakfast'],
  },
  {
    id: 'staple-3',
    name: 'French Toast',
    description: 'Classic French toast with a custardy center and crispy edges.',
    image: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800',
    prepTime: 5,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'French',
    category: 'Breakfast',
    ingredients: [
      { item: 'thick bread slices', amount: '8' },
      { item: 'eggs', amount: '4' },
      { item: 'milk', amount: '1 cup' },
      { item: 'vanilla extract', amount: '1 tsp' },
      { item: 'cinnamon', amount: '1/2 tsp' },
      { item: 'sugar', amount: '2 tbsp' },
      { item: 'butter', amount: 'for cooking' },
    ],
    instructions: [
      'Whisk together eggs, milk, vanilla, cinnamon, and sugar in a shallow dish.',
      'Heat butter in a large skillet over medium heat.',
      'Dip each bread slice in egg mixture, coating both sides well.',
      'Let excess drip off, then place in hot pan.',
      'Cook 2-3 minutes per side until golden brown.',
      'Serve with maple syrup, powdered sugar, or fresh berries.',
    ],
    tags: ['breakfast', 'french-toast', 'brunch', 'vegetarian'],
    mealType: ['Breakfast'],
  },
  {
    id: 'staple-4',
    name: 'Classic Oatmeal',
    description: 'Creamy stovetop oatmeal that can be customized with your favorite toppings.',
    image: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800',
    prepTime: 2,
    cookTime: 10,
    servings: 2,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Breakfast',
    ingredients: [
      { item: 'rolled oats', amount: '1 cup' },
      { item: 'water or milk', amount: '2 cups' },
      { item: 'salt', amount: 'pinch' },
      { item: 'honey or maple syrup', amount: '2 tbsp', optional: true },
      { item: 'fresh berries', amount: '1/2 cup', optional: true },
    ],
    instructions: [
      'Bring water or milk to a boil in a saucepan.',
      'Stir in oats and reduce heat to medium-low.',
      'Cook for 5 minutes, stirring occasionally.',
      'Remove from heat and let stand for 1 minute.',
      'Top with honey, berries, nuts, or your favorite toppings.',
    ],
    tags: ['breakfast', 'oatmeal', 'healthy', 'vegan', 'quick'],
    mealType: ['Breakfast'],
  },
  {
    id: 'staple-5',
    name: 'Avocado Toast',
    description: 'Trendy and nutritious toast topped with creamy mashed avocado.',
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800',
    prepTime: 5,
    cookTime: 5,
    servings: 2,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Breakfast',
    ingredients: [
      { item: 'bread slices', amount: '2, thick cut' },
      { item: 'ripe avocado', amount: '1 large' },
      { item: 'lemon juice', amount: '1 tsp' },
      { item: 'salt', amount: '1/4 tsp' },
      { item: 'red pepper flakes', amount: 'pinch', optional: true },
      { item: 'everything bagel seasoning', amount: '1 tsp', optional: true },
    ],
    instructions: [
      'Toast bread slices until golden and crispy.',
      'Cut avocado in half, remove pit, and scoop flesh into a bowl.',
      'Add lemon juice and salt, mash with a fork to desired consistency.',
      'Spread avocado mixture generously on each toast.',
      'Top with red pepper flakes or everything bagel seasoning.',
      'Serve immediately while toast is still warm.',
    ],
    tags: ['breakfast', 'avocado', 'toast', 'healthy', 'vegan', 'quick'],
    mealType: ['Breakfast', 'Snack'],
  },
  {
    id: 'staple-6',
    name: 'Eggs Benedict',
    description: 'Elegant brunch classic with poached eggs, Canadian bacon, and hollandaise sauce.',
    image: 'https://images.unsplash.com/photo-1608039829572-f9e0e9a80b53?w=800',
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: 'Medium',
    cuisine: 'American',
    category: 'Breakfast',
    ingredients: [
      { item: 'English muffins', amount: '4, split' },
      { item: 'Canadian bacon', amount: '8 slices' },
      { item: 'eggs', amount: '8' },
      { item: 'egg yolks', amount: '3' },
      { item: 'butter', amount: '1/2 cup, melted' },
      { item: 'lemon juice', amount: '1 tbsp' },
      { item: 'white vinegar', amount: '1 tbsp' },
      { item: 'salt and cayenne', amount: 'to taste' },
    ],
    instructions: [
      'For hollandaise: Blend egg yolks and lemon juice in blender. Slowly drizzle in hot melted butter while blending. Season with salt and cayenne.',
      'Toast English muffins and keep warm.',
      'Pan-fry Canadian bacon until slightly crispy. Keep warm.',
      'Bring a pot of water to simmer with vinegar. Create a gentle whirlpool.',
      'Crack eggs one at a time into the water. Poach for 3-4 minutes until whites are set but yolks are runny.',
      'Assemble: muffin, bacon, poached egg, drizzle of hollandaise.',
      'Serve immediately with fresh cracked pepper.',
    ],
    tags: ['breakfast', 'brunch', 'eggs', 'elegant'],
    mealType: ['Breakfast', 'Brunch'],
  },
  {
    id: 'staple-7',
    name: 'Breakfast Burrito',
    description: 'Hearty flour tortilla stuffed with scrambled eggs, cheese, and your choice of fillings.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'Mexican',
    category: 'Breakfast',
    ingredients: [
      { item: 'large flour tortillas', amount: '4' },
      { item: 'eggs', amount: '6, scrambled' },
      { item: 'shredded cheese', amount: '1 cup' },
      { item: 'breakfast sausage or bacon', amount: '8 oz, cooked' },
      { item: 'hash browns', amount: '1 cup, cooked', optional: true },
      { item: 'salsa', amount: '1/2 cup' },
      { item: 'sour cream', amount: '1/4 cup', optional: true },
    ],
    instructions: [
      'Scramble eggs in a pan until just set. Season with salt and pepper.',
      'Warm tortillas in a dry pan or microwave.',
      'Layer eggs, cheese, meat, and hash browns down the center of each tortilla.',
      'Add salsa and sour cream.',
      'Fold in sides, then roll up tightly from bottom to top.',
      'Optional: grill seam-side down for a crispy exterior.',
    ],
    tags: ['breakfast', 'burrito', 'mexican', 'filling'],
    mealType: ['Breakfast'],
  },

  // ============ LUNCH STAPLES ============
  {
    id: 'staple-8',
    name: 'Classic Grilled Cheese',
    description: 'The ultimate comfort food - crispy buttered bread with melty cheese.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800',
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Breakfast',
    ingredients: [
      { item: 'bread slices', amount: '2' },
      { item: 'cheddar cheese', amount: '2-3 slices' },
      { item: 'butter', amount: '2 tbsp, softened' },
    ],
    instructions: [
      'Butter one side of each bread slice generously.',
      'Heat a non-stick pan over medium-low heat.',
      'Place one bread slice butter-side down in the pan.',
      'Layer cheese slices on top of the bread.',
      'Place second bread slice on top, butter-side up.',
      'Cook for 3-4 minutes until bottom is golden brown.',
      'Flip carefully and cook other side for 3-4 minutes.',
      'Remove when both sides are golden and cheese is melted.',
    ],
    tags: ['lunch', 'sandwich', 'cheese', 'comfort-food', 'vegetarian', 'quick'],
    mealType: ['Lunch', 'Snack'],
  },
  {
    id: 'staple-9',
    name: 'BLT Sandwich',
    description: 'Classic bacon, lettuce, and tomato sandwich on toasted bread with mayo.',
    image: 'https://images.unsplash.com/photo-1619096252214-ef06c45683e3?w=800',
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Miscellaneous',
    ingredients: [
      { item: 'bacon strips', amount: '8' },
      { item: 'bread slices', amount: '4, toasted' },
      { item: 'lettuce leaves', amount: '4' },
      { item: 'tomato', amount: '1 large, sliced' },
      { item: 'mayonnaise', amount: '2 tbsp' },
      { item: 'salt and pepper', amount: 'to taste' },
    ],
    instructions: [
      'Cook bacon in a skillet until crispy. Drain on paper towels.',
      'Toast bread slices until golden.',
      'Spread mayonnaise on one side of each bread slice.',
      'Layer lettuce, tomato slices, and bacon on two slices.',
      'Season with salt and pepper.',
      'Top with remaining bread slices, mayo-side down.',
      'Cut diagonally and serve.',
    ],
    tags: ['lunch', 'sandwich', 'bacon', 'classic'],
    mealType: ['Lunch'],
  },
  {
    id: 'staple-10',
    name: 'Chicken Salad Sandwich',
    description: 'Creamy chicken salad with celery and herbs, perfect for sandwiches or crackers.',
    image: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?w=800',
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Chicken',
    ingredients: [
      { item: 'cooked chicken', amount: '2 cups, shredded or diced' },
      { item: 'mayonnaise', amount: '1/2 cup' },
      { item: 'celery', amount: '1/2 cup, diced' },
      { item: 'red onion', amount: '2 tbsp, minced' },
      { item: 'dijon mustard', amount: '1 tsp' },
      { item: 'lemon juice', amount: '1 tbsp' },
      { item: 'salt and pepper', amount: 'to taste' },
      { item: 'bread or croissants', amount: 'for serving' },
    ],
    instructions: [
      'In a large bowl, combine shredded chicken, mayonnaise, and mustard.',
      'Add celery and red onion, mix well.',
      'Stir in lemon juice and season with salt and pepper.',
      'Refrigerate for 30 minutes to let flavors meld.',
      'Serve on bread, croissants, or with crackers.',
    ],
    tags: ['lunch', 'chicken', 'salad', 'sandwich'],
    mealType: ['Lunch'],
  },
  {
    id: 'staple-11',
    name: 'Tomato Soup',
    description: 'Creamy homemade tomato soup that pairs perfectly with grilled cheese.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Soup',
    ingredients: [
      { item: 'canned whole tomatoes', amount: '28 oz can' },
      { item: 'onion', amount: '1 medium, diced' },
      { item: 'garlic', amount: '3 cloves, minced' },
      { item: 'vegetable broth', amount: '2 cups' },
      { item: 'heavy cream', amount: '1/2 cup' },
      { item: 'butter', amount: '2 tbsp' },
      { item: 'sugar', amount: '1 tsp' },
      { item: 'dried basil', amount: '1 tsp' },
    ],
    instructions: [
      'Melt butter in a large pot over medium heat.',
      'Add diced onion and cook for 5 minutes until softened.',
      'Add garlic and cook for 1 minute until fragrant.',
      'Add canned tomatoes, broth, sugar, and basil.',
      'Bring to a boil, reduce heat, and simmer for 20 minutes.',
      'Blend until smooth with an immersion blender.',
      'Stir in heavy cream and heat through.',
      'Season with salt and pepper to taste.',
    ],
    tags: ['soup', 'tomato', 'comfort-food', 'vegetarian', 'lunch'],
    mealType: ['Lunch', 'Dinner'],
  },
  {
    id: 'staple-12',
    name: 'Caesar Salad',
    description: 'Classic Caesar with crisp romaine, parmesan, croutons, and creamy dressing.',
    image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=800',
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'Italian',
    category: 'Side',
    ingredients: [
      { item: 'romaine lettuce', amount: '2 heads, chopped' },
      { item: 'parmesan cheese', amount: '1/2 cup, shaved' },
      { item: 'croutons', amount: '1 cup' },
      { item: 'mayonnaise', amount: '1/2 cup' },
      { item: 'lemon juice', amount: '2 tbsp' },
      { item: 'garlic', amount: '2 cloves, minced' },
      { item: 'dijon mustard', amount: '1 tsp' },
      { item: 'worcestershire sauce', amount: '1 tsp' },
    ],
    instructions: [
      'Whisk together mayo, lemon juice, garlic, mustard, and worcestershire for dressing.',
      'Season with salt and pepper to taste.',
      'Wash and dry romaine lettuce, chop into bite-sized pieces.',
      'Toss lettuce with dressing until well coated.',
      'Add croutons and half the parmesan, toss again.',
      'Serve topped with remaining parmesan.',
    ],
    tags: ['salad', 'caesar', 'side', 'lunch', 'healthy'],
    mealType: ['Lunch', 'Side'],
  },
  {
    id: 'staple-13',
    name: 'Quesadilla',
    description: 'Crispy tortilla filled with melted cheese and your choice of fillings.',
    image: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=800',
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    difficulty: 'Easy',
    cuisine: 'Mexican',
    category: 'Miscellaneous',
    ingredients: [
      { item: 'large flour tortillas', amount: '2' },
      { item: 'shredded cheese', amount: '1.5 cups' },
      { item: 'butter', amount: '1 tbsp' },
      { item: 'salsa', amount: 'for serving' },
      { item: 'sour cream', amount: 'for serving' },
    ],
    instructions: [
      'Heat a large skillet over medium heat.',
      'Place one tortilla in the pan.',
      'Sprinkle cheese evenly over the tortilla.',
      'Top with second tortilla.',
      'Cook 2-3 minutes until bottom is golden and cheese starts to melt.',
      'Flip carefully and cook another 2-3 minutes.',
      'Cut into wedges and serve with salsa and sour cream.',
    ],
    tags: ['lunch', 'mexican', 'cheese', 'quick', 'vegetarian'],
    mealType: ['Lunch', 'Snack'],
  },

  // ============ DINNER STAPLES ============
  {
    id: 'staple-14',
    name: 'Spaghetti and Meatballs',
    description: 'Classic Italian-American comfort food with homemade meatballs in marinara sauce.',
    image: 'https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=800',
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    difficulty: 'Medium',
    cuisine: 'Italian',
    category: 'Pasta',
    ingredients: [
      { item: 'spaghetti', amount: '1 lb' },
      { item: 'ground beef', amount: '1 lb' },
      { item: 'breadcrumbs', amount: '1/2 cup' },
      { item: 'egg', amount: '1' },
      { item: 'parmesan cheese', amount: '1/4 cup, grated' },
      { item: 'garlic', amount: '3 cloves, minced' },
      { item: 'marinara sauce', amount: '24 oz jar' },
      { item: 'Italian seasoning', amount: '1 tsp' },
    ],
    instructions: [
      'Mix ground beef, breadcrumbs, egg, parmesan, half the garlic, and Italian seasoning.',
      'Form into 1.5-inch meatballs.',
      'Brown meatballs in a large skillet over medium-high heat.',
      'Add marinara sauce and remaining garlic. Simmer for 20 minutes.',
      'Meanwhile, cook spaghetti according to package directions.',
      'Drain pasta and serve topped with meatballs and sauce.',
      'Garnish with fresh parsley and extra parmesan.',
    ],
    tags: ['dinner', 'pasta', 'italian', 'meatballs', 'comfort-food'],
    mealType: ['Dinner'],
  },
  {
    id: 'staple-15',
    name: 'Garlic Butter Pasta',
    description: 'Simple yet delicious pasta in garlic-infused butter with parmesan.',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'Italian',
    category: 'Pasta',
    ingredients: [
      { item: 'spaghetti or linguine', amount: '1 lb' },
      { item: 'butter', amount: '4 tbsp' },
      { item: 'garlic', amount: '6 cloves, minced' },
      { item: 'olive oil', amount: '2 tbsp' },
      { item: 'parmesan cheese', amount: '1/2 cup, grated' },
      { item: 'fresh parsley', amount: '1/4 cup, chopped' },
      { item: 'red pepper flakes', amount: '1/4 tsp', optional: true },
    ],
    instructions: [
      'Cook pasta according to package directions. Reserve 1 cup pasta water.',
      'Melt butter with olive oil in a large pan over medium heat.',
      'Add garlic and cook 1-2 minutes until fragrant but not browned.',
      'Add drained pasta to the pan and toss to coat.',
      'Add pasta water as needed to create a light sauce.',
      'Remove from heat, add parmesan and parsley, toss well.',
      'Season with salt, pepper, and red pepper flakes.',
    ],
    tags: ['dinner', 'pasta', 'italian', 'garlic', 'quick', 'vegetarian'],
    mealType: ['Dinner', 'Lunch'],
  },
  {
    id: 'staple-16',
    name: 'Baked Chicken Breast',
    description: 'Juicy, perfectly seasoned baked chicken breast - a versatile protein staple.',
    image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800',
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Chicken',
    ingredients: [
      { item: 'chicken breasts', amount: '4, boneless skinless' },
      { item: 'olive oil', amount: '2 tbsp' },
      { item: 'garlic powder', amount: '1 tsp' },
      { item: 'paprika', amount: '1 tsp' },
      { item: 'Italian seasoning', amount: '1 tsp' },
      { item: 'salt', amount: '1 tsp' },
      { item: 'black pepper', amount: '1/2 tsp' },
    ],
    instructions: [
      'Preheat oven to 425°F (220°C).',
      'Pound chicken to even thickness if needed.',
      'Rub chicken with olive oil.',
      'Mix all seasonings and coat chicken evenly on both sides.',
      'Place on a baking sheet lined with parchment paper.',
      'Bake for 20-25 minutes until internal temperature reaches 165°F.',
      'Rest for 5 minutes before slicing.',
    ],
    tags: ['dinner', 'chicken', 'healthy', 'meal-prep', 'protein'],
    mealType: ['Dinner', 'Lunch'],
  },
  {
    id: 'staple-17',
    name: 'Beef Tacos',
    description: 'Seasoned ground beef in crispy taco shells with all the fixings.',
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'Mexican',
    category: 'Beef',
    ingredients: [
      { item: 'ground beef', amount: '1 lb' },
      { item: 'taco shells', amount: '8' },
      { item: 'taco seasoning', amount: '2 tbsp' },
      { item: 'water', amount: '1/2 cup' },
      { item: 'shredded lettuce', amount: '2 cups' },
      { item: 'diced tomatoes', amount: '1 cup' },
      { item: 'shredded cheese', amount: '1 cup' },
      { item: 'sour cream', amount: '1/2 cup' },
      { item: 'salsa', amount: '1/2 cup' },
    ],
    instructions: [
      'Brown ground beef in a skillet over medium-high heat.',
      'Drain excess fat.',
      'Add taco seasoning and water, simmer 5 minutes until thickened.',
      'Warm taco shells according to package directions.',
      'Fill shells with beef.',
      'Top with lettuce, tomatoes, cheese, sour cream, and salsa.',
    ],
    tags: ['dinner', 'mexican', 'tacos', 'beef', 'quick'],
    mealType: ['Dinner'],
  },
  {
    id: 'staple-18',
    name: 'Chicken Stir Fry',
    description: 'Quick and healthy chicken with colorful vegetables in a savory sauce.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800',
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'Chinese',
    category: 'Chicken',
    ingredients: [
      { item: 'chicken breast', amount: '1 lb, sliced thin' },
      { item: 'broccoli florets', amount: '2 cups' },
      { item: 'bell peppers', amount: '2, sliced' },
      { item: 'soy sauce', amount: '3 tbsp' },
      { item: 'sesame oil', amount: '1 tbsp' },
      { item: 'garlic', amount: '3 cloves, minced' },
      { item: 'ginger', amount: '1 tbsp, minced' },
      { item: 'vegetable oil', amount: '2 tbsp' },
      { item: 'cornstarch', amount: '1 tbsp' },
    ],
    instructions: [
      'Mix soy sauce, sesame oil, and cornstarch in a bowl.',
      'Heat vegetable oil in a wok over high heat.',
      'Cook chicken 3-4 minutes until golden. Remove and set aside.',
      'Add broccoli and peppers, stir fry 3 minutes.',
      'Add garlic and ginger, cook 30 seconds.',
      'Return chicken to wok with sauce.',
      'Toss until sauce thickens, about 2 minutes.',
      'Serve over steamed rice.',
    ],
    tags: ['dinner', 'chicken', 'stir-fry', 'chinese', 'healthy', 'quick'],
    mealType: ['Dinner'],
  },
  {
    id: 'staple-19',
    name: 'Fried Rice',
    description: 'Restaurant-style fried rice made easy at home with day-old rice.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'Chinese',
    category: 'Side',
    ingredients: [
      { item: 'cooked rice', amount: '4 cups, day-old' },
      { item: 'eggs', amount: '2, beaten' },
      { item: 'frozen peas and carrots', amount: '1 cup' },
      { item: 'green onions', amount: '4, chopped' },
      { item: 'soy sauce', amount: '3 tbsp' },
      { item: 'sesame oil', amount: '1 tbsp' },
      { item: 'vegetable oil', amount: '2 tbsp' },
      { item: 'garlic', amount: '2 cloves, minced' },
    ],
    instructions: [
      'Heat 1 tbsp oil in a wok over high heat.',
      'Scramble eggs quickly and remove.',
      'Add remaining oil and frozen vegetables, cook 2 minutes.',
      'Add garlic, cook 30 seconds.',
      'Add rice, breaking up clumps. Stir fry 3-4 minutes.',
      'Add soy sauce and sesame oil, toss well.',
      'Add eggs and green onions, toss to combine.',
    ],
    tags: ['dinner', 'rice', 'chinese', 'quick', 'vegetarian'],
    mealType: ['Dinner', 'Side'],
  },
  {
    id: 'staple-20',
    name: 'Baked Salmon',
    description: 'Simple baked salmon with lemon and herbs - elegant yet easy.',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
    prepTime: 5,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Seafood',
    ingredients: [
      { item: 'salmon fillets', amount: '4 (6 oz each)' },
      { item: 'olive oil', amount: '2 tbsp' },
      { item: 'lemon', amount: '1, sliced' },
      { item: 'garlic', amount: '3 cloves, minced' },
      { item: 'fresh dill', amount: '2 tbsp, chopped' },
      { item: 'salt and pepper', amount: 'to taste' },
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Place salmon on a lined baking sheet.',
      'Drizzle with olive oil and rub with garlic.',
      'Season with salt, pepper, and dill.',
      'Top with lemon slices.',
      'Bake 12-15 minutes until salmon flakes easily.',
      'Serve with additional lemon wedges.',
    ],
    tags: ['dinner', 'salmon', 'seafood', 'healthy', 'quick'],
    mealType: ['Dinner'],
  },
  {
    id: 'staple-21',
    name: 'Hamburgers',
    description: 'Classic juicy beef burgers grilled to perfection.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800',
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Beef',
    ingredients: [
      { item: 'ground beef (80/20)', amount: '1.5 lbs' },
      { item: 'hamburger buns', amount: '4' },
      { item: 'salt', amount: '1 tsp' },
      { item: 'pepper', amount: '1/2 tsp' },
      { item: 'cheese slices', amount: '4', optional: true },
      { item: 'lettuce, tomato, onion', amount: 'for topping' },
    ],
    instructions: [
      'Divide beef into 4 portions and form into patties slightly larger than buns.',
      'Make a small indent in the center of each patty to prevent puffing.',
      'Season generously with salt and pepper.',
      'Grill or pan-fry over medium-high heat, 4 minutes per side for medium.',
      'Add cheese in the last minute if desired.',
      'Toast buns lightly on the grill.',
      'Assemble with your favorite toppings.',
    ],
    tags: ['dinner', 'burger', 'beef', 'grilling', 'american'],
    mealType: ['Dinner', 'Lunch'],
  },
  {
    id: 'staple-22',
    name: 'Mac and Cheese',
    description: 'Creamy, cheesy homemade mac and cheese that beats any box.',
    image: 'https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?w=800',
    prepTime: 10,
    cookTime: 25,
    servings: 6,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Pasta',
    ingredients: [
      { item: 'elbow macaroni', amount: '1 lb' },
      { item: 'butter', amount: '4 tbsp' },
      { item: 'all-purpose flour', amount: '4 tbsp' },
      { item: 'milk', amount: '3 cups' },
      { item: 'sharp cheddar cheese', amount: '3 cups, shredded' },
      { item: 'salt', amount: '1 tsp' },
      { item: 'mustard powder', amount: '1/2 tsp', optional: true },
    ],
    instructions: [
      'Cook macaroni according to package directions. Drain and set aside.',
      'Melt butter in a large pot over medium heat.',
      'Whisk in flour and cook 1 minute.',
      'Gradually whisk in milk. Cook until thickened, about 5 minutes.',
      'Remove from heat and stir in cheese until melted.',
      'Season with salt and mustard powder.',
      'Add cooked macaroni and stir to coat.',
    ],
    tags: ['dinner', 'pasta', 'cheese', 'comfort-food', 'vegetarian'],
    mealType: ['Dinner', 'Side'],
  },
  {
    id: 'staple-23',
    name: 'Roast Chicken',
    description: 'Perfectly roasted whole chicken with crispy skin and juicy meat.',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800',
    prepTime: 15,
    cookTime: 75,
    servings: 6,
    difficulty: 'Medium',
    cuisine: 'American',
    category: 'Chicken',
    ingredients: [
      { item: 'whole chicken', amount: '4-5 lbs' },
      { item: 'butter', amount: '4 tbsp, softened' },
      { item: 'garlic', amount: '4 cloves, minced' },
      { item: 'lemon', amount: '1, halved' },
      { item: 'fresh thyme', amount: '4 sprigs' },
      { item: 'salt', amount: '2 tsp' },
      { item: 'pepper', amount: '1 tsp' },
    ],
    instructions: [
      'Preheat oven to 425°F (220°C).',
      'Pat chicken dry and let come to room temperature.',
      'Mix butter with garlic, salt, and pepper.',
      'Rub butter under and over the skin.',
      'Stuff cavity with lemon halves and thyme.',
      'Tie legs together with kitchen twine.',
      'Roast for 1 hour 15 minutes until internal temp reaches 165°F.',
      'Rest 15 minutes before carving.',
    ],
    tags: ['dinner', 'chicken', 'roast', 'sunday-dinner'],
    mealType: ['Dinner'],
  },
  {
    id: 'staple-24',
    name: 'Beef Stew',
    description: 'Hearty slow-cooked beef stew with tender vegetables.',
    image: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800',
    prepTime: 20,
    cookTime: 120,
    servings: 6,
    difficulty: 'Medium',
    cuisine: 'American',
    category: 'Beef',
    ingredients: [
      { item: 'beef stew meat', amount: '2 lbs, cubed' },
      { item: 'potatoes', amount: '4, cubed' },
      { item: 'carrots', amount: '4, sliced' },
      { item: 'onion', amount: '1 large, diced' },
      { item: 'beef broth', amount: '4 cups' },
      { item: 'tomato paste', amount: '2 tbsp' },
      { item: 'flour', amount: '3 tbsp' },
      { item: 'worcestershire sauce', amount: '1 tbsp' },
    ],
    instructions: [
      'Season beef with salt and pepper, coat lightly with flour.',
      'Brown beef in batches in a Dutch oven. Remove and set aside.',
      'Sauté onion until softened.',
      'Add tomato paste and cook 1 minute.',
      'Add broth and worcestershire, scraping up browned bits.',
      'Return beef to pot. Bring to a simmer.',
      'Cover and cook 1 hour.',
      'Add potatoes and carrots, cook another hour until tender.',
    ],
    tags: ['dinner', 'beef', 'stew', 'comfort-food', 'winter'],
    mealType: ['Dinner'],
  },
  {
    id: 'staple-25',
    name: 'Mashed Potatoes',
    description: 'Creamy, buttery mashed potatoes - the perfect side dish.',
    image: 'https://images.unsplash.com/photo-1585672840563-f2af2ced55c9?w=800',
    prepTime: 10,
    cookTime: 20,
    servings: 6,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Side',
    ingredients: [
      { item: 'russet potatoes', amount: '3 lbs, peeled and cubed' },
      { item: 'butter', amount: '6 tbsp' },
      { item: 'milk or cream', amount: '1 cup, warmed' },
      { item: 'salt', amount: '1 tsp' },
      { item: 'pepper', amount: 'to taste' },
      { item: 'garlic', amount: '2 cloves, optional' },
    ],
    instructions: [
      'Place potatoes in a large pot, cover with cold salted water.',
      'Add garlic if using. Bring to a boil.',
      'Cook 15-20 minutes until fork-tender.',
      'Drain well and return to pot.',
      'Add butter and mash until smooth.',
      'Gradually add warm milk, mashing to desired consistency.',
      'Season with salt and pepper.',
    ],
    tags: ['side', 'potatoes', 'comfort-food', 'vegetarian'],
    mealType: ['Side', 'Dinner'],
  },
  {
    id: 'staple-26',
    name: 'Chili',
    description: 'Hearty beef and bean chili with warm spices.',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800',
    prepTime: 15,
    cookTime: 45,
    servings: 8,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Beef',
    ingredients: [
      { item: 'ground beef', amount: '2 lbs' },
      { item: 'kidney beans', amount: '2 cans, drained' },
      { item: 'diced tomatoes', amount: '28 oz can' },
      { item: 'onion', amount: '1 large, diced' },
      { item: 'garlic', amount: '4 cloves, minced' },
      { item: 'chili powder', amount: '3 tbsp' },
      { item: 'cumin', amount: '1 tbsp' },
      { item: 'tomato paste', amount: '2 tbsp' },
    ],
    instructions: [
      'Brown ground beef with onion in a large pot.',
      'Add garlic, cook 1 minute.',
      'Stir in chili powder, cumin, and tomato paste.',
      'Add tomatoes and beans.',
      'Simmer 30-45 minutes, stirring occasionally.',
      'Season with salt and pepper.',
      'Serve with cheese, sour cream, and green onions.',
    ],
    tags: ['dinner', 'chili', 'beef', 'beans', 'comfort-food'],
    mealType: ['Dinner'],
  },
  {
    id: 'staple-27',
    name: 'Pizza Dough',
    description: 'Homemade pizza dough that makes crispy, chewy crust.',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800',
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    difficulty: 'Medium',
    cuisine: 'Italian',
    category: 'Miscellaneous',
    ingredients: [
      { item: 'all-purpose flour', amount: '2.5 cups' },
      { item: 'active dry yeast', amount: '1 packet' },
      { item: 'warm water', amount: '1 cup' },
      { item: 'olive oil', amount: '2 tbsp' },
      { item: 'sugar', amount: '1 tsp' },
      { item: 'salt', amount: '1 tsp' },
    ],
    instructions: [
      'Dissolve yeast and sugar in warm water. Let sit 5 minutes until foamy.',
      'Mix flour and salt in a large bowl.',
      'Add yeast mixture and olive oil, stir until dough forms.',
      'Knead on floured surface for 5-7 minutes until smooth.',
      'Place in oiled bowl, cover, and let rise 1 hour.',
      'Punch down and divide into 2 balls.',
      'Roll out and add your favorite toppings.',
      'Bake at 475°F for 12-15 minutes.',
    ],
    tags: ['pizza', 'dough', 'italian', 'baking'],
    mealType: ['Dinner'],
  },
  {
    id: 'staple-28',
    name: 'Chicken Noodle Soup',
    description: 'Comforting homemade chicken noodle soup for the soul.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Soup',
    ingredients: [
      { item: 'chicken breast', amount: '1 lb' },
      { item: 'egg noodles', amount: '8 oz' },
      { item: 'chicken broth', amount: '8 cups' },
      { item: 'carrots', amount: '3, sliced' },
      { item: 'celery', amount: '3 stalks, sliced' },
      { item: 'onion', amount: '1, diced' },
      { item: 'garlic', amount: '2 cloves, minced' },
      { item: 'fresh thyme', amount: '2 sprigs' },
    ],
    instructions: [
      'Bring broth to boil in a large pot.',
      'Add chicken breasts and simmer 15 minutes until cooked.',
      'Remove chicken, shred, and set aside.',
      'Add carrots, celery, onion, garlic, and thyme to broth.',
      'Simmer 10 minutes until vegetables are tender.',
      'Add noodles and cook until al dente.',
      'Return shredded chicken to pot.',
      'Season with salt and pepper. Serve hot.',
    ],
    tags: ['soup', 'chicken', 'noodles', 'comfort-food', 'sick-day'],
    mealType: ['Lunch', 'Dinner'],
  },
  {
    id: 'staple-29',
    name: 'Lasagna',
    description: 'Layered pasta with meat sauce, ricotta, and melted mozzarella.',
    image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800',
    prepTime: 30,
    cookTime: 60,
    servings: 8,
    difficulty: 'Medium',
    cuisine: 'Italian',
    category: 'Pasta',
    ingredients: [
      { item: 'lasagna noodles', amount: '12' },
      { item: 'ground beef', amount: '1 lb' },
      { item: 'marinara sauce', amount: '24 oz' },
      { item: 'ricotta cheese', amount: '15 oz' },
      { item: 'mozzarella cheese', amount: '3 cups, shredded' },
      { item: 'parmesan cheese', amount: '1/2 cup, grated' },
      { item: 'egg', amount: '1' },
      { item: 'Italian seasoning', amount: '1 tbsp' },
    ],
    instructions: [
      'Cook noodles according to package. Brown beef, drain, mix with marinara.',
      'Mix ricotta, egg, half the mozzarella, and Italian seasoning.',
      'Spread 1/2 cup sauce in 9x13 baking dish.',
      'Layer: 3 noodles, 1/3 ricotta mixture, 1/3 meat sauce. Repeat twice.',
      'Top with remaining noodles, sauce, mozzarella, and parmesan.',
      'Cover with foil and bake at 375°F for 45 minutes.',
      'Uncover and bake 15 more minutes until bubbly.',
      'Rest 15 minutes before cutting.',
    ],
    tags: ['dinner', 'pasta', 'italian', 'lasagna', 'comfort-food'],
    mealType: ['Dinner'],
  },
  {
    id: 'staple-30',
    name: 'Curry Chicken',
    description: 'Aromatic chicken curry with tender pieces in a rich, spiced sauce.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800',
    prepTime: 15,
    cookTime: 35,
    servings: 4,
    difficulty: 'Medium',
    cuisine: 'Indian',
    category: 'Chicken',
    ingredients: [
      { item: 'chicken thighs', amount: '1.5 lbs, cubed' },
      { item: 'coconut milk', amount: '14 oz can' },
      { item: 'onion', amount: '1 large, diced' },
      { item: 'garlic', amount: '4 cloves, minced' },
      { item: 'ginger', amount: '1 tbsp, minced' },
      { item: 'curry powder', amount: '2 tbsp' },
      { item: 'tomato paste', amount: '2 tbsp' },
      { item: 'chicken broth', amount: '1/2 cup' },
    ],
    instructions: [
      'Season chicken with salt and pepper.',
      'Brown chicken in a large pan. Remove and set aside.',
      'Sauté onion until softened.',
      'Add garlic, ginger, and curry powder. Cook 1 minute.',
      'Stir in tomato paste, then add coconut milk and broth.',
      'Return chicken to pan, simmer 20-25 minutes.',
      'Adjust seasoning and serve over rice.',
    ],
    tags: ['dinner', 'chicken', 'curry', 'indian', 'spicy'],
    mealType: ['Dinner'],
  },

  // ============ SIDE DISHES ============
  {
    id: 'staple-31',
    name: 'Steamed Rice',
    description: 'Perfectly fluffy steamed white rice every time.',
    image: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=800',
    prepTime: 5,
    cookTime: 20,
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'Asian',
    category: 'Side',
    ingredients: [
      { item: 'long grain white rice', amount: '1 cup' },
      { item: 'water', amount: '2 cups' },
      { item: 'salt', amount: '1/2 tsp' },
    ],
    instructions: [
      'Rinse rice under cold water until water runs clear.',
      'Combine rice, water, and salt in a pot.',
      'Bring to a boil over high heat.',
      'Reduce heat to low, cover tightly.',
      'Simmer for 18 minutes without lifting lid.',
      'Remove from heat and let stand covered 5 minutes.',
      'Fluff with a fork and serve.',
    ],
    tags: ['side', 'rice', 'basic', 'vegan'],
    mealType: ['Side'],
  },
  {
    id: 'staple-32',
    name: 'Roasted Vegetables',
    description: 'Caramelized roasted vegetables with olive oil and herbs.',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    prepTime: 15,
    cookTime: 35,
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Side',
    ingredients: [
      { item: 'mixed vegetables', amount: '2 lbs (broccoli, carrots, peppers, zucchini)' },
      { item: 'olive oil', amount: '3 tbsp' },
      { item: 'garlic', amount: '3 cloves, minced' },
      { item: 'Italian seasoning', amount: '1 tsp' },
      { item: 'salt', amount: '1 tsp' },
      { item: 'pepper', amount: '1/2 tsp' },
    ],
    instructions: [
      'Preheat oven to 425°F (220°C).',
      'Cut vegetables into similar-sized pieces.',
      'Toss with olive oil, garlic, and seasonings.',
      'Spread in single layer on baking sheets.',
      'Roast 30-35 minutes, stirring halfway.',
      'Vegetables should be tender and caramelized.',
    ],
    tags: ['side', 'vegetables', 'healthy', 'vegan', 'roasted'],
    mealType: ['Side', 'Dinner'],
  },
  {
    id: 'staple-33',
    name: 'Coleslaw',
    description: 'Creamy, tangy coleslaw perfect for BBQs and sandwiches.',
    image: 'https://images.unsplash.com/photo-1528735000313-0d3e3ec76c15?w=800',
    prepTime: 15,
    cookTime: 0,
    servings: 8,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Side',
    ingredients: [
      { item: 'cabbage', amount: '1 head, shredded' },
      { item: 'carrots', amount: '2, shredded' },
      { item: 'mayonnaise', amount: '1 cup' },
      { item: 'apple cider vinegar', amount: '2 tbsp' },
      { item: 'sugar', amount: '2 tbsp' },
      { item: 'salt', amount: '1/2 tsp' },
    ],
    instructions: [
      'Combine shredded cabbage and carrots in a large bowl.',
      'Whisk together mayonnaise, vinegar, sugar, and salt.',
      'Pour dressing over vegetables and toss well.',
      'Refrigerate at least 1 hour before serving.',
      'Toss again before serving.',
    ],
    tags: ['side', 'salad', 'coleslaw', 'bbq', 'vegetarian'],
    mealType: ['Side'],
  },
  {
    id: 'staple-34',
    name: 'Garlic Bread',
    description: 'Crispy, buttery garlic bread that complements any Italian meal.',
    image: 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=800',
    prepTime: 10,
    cookTime: 10,
    servings: 8,
    difficulty: 'Easy',
    cuisine: 'Italian',
    category: 'Side',
    ingredients: [
      { item: 'French baguette', amount: '1' },
      { item: 'butter', amount: '1/2 cup, softened' },
      { item: 'garlic', amount: '4 cloves, minced' },
      { item: 'fresh parsley', amount: '2 tbsp, chopped' },
      { item: 'parmesan cheese', amount: '1/4 cup, grated', optional: true },
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Mix softened butter with garlic and parsley.',
      'Slice baguette in half lengthwise.',
      'Spread garlic butter generously on cut sides.',
      'Sprinkle with parmesan if desired.',
      'Bake 10-12 minutes until golden and crispy.',
      'Slice and serve warm.',
    ],
    tags: ['side', 'bread', 'garlic', 'italian', 'vegetarian'],
    mealType: ['Side'],
  },

  // ============ DESSERTS ============
  {
    id: 'staple-35',
    name: 'Chocolate Chip Cookies',
    description: 'Classic chewy cookies with crispy edges and gooey chocolate chips.',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800',
    prepTime: 15,
    cookTime: 12,
    servings: 24,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Dessert',
    ingredients: [
      { item: 'all-purpose flour', amount: '2.25 cups' },
      { item: 'butter', amount: '1 cup, softened' },
      { item: 'brown sugar', amount: '3/4 cup, packed' },
      { item: 'white sugar', amount: '1/4 cup' },
      { item: 'eggs', amount: '2' },
      { item: 'vanilla extract', amount: '1 tsp' },
      { item: 'baking soda', amount: '1 tsp' },
      { item: 'chocolate chips', amount: '2 cups' },
    ],
    instructions: [
      'Preheat oven to 375°F (190°C).',
      'Whisk flour, baking soda, and salt. Set aside.',
      'Beat butter and sugars until fluffy.',
      'Beat in eggs one at a time, then vanilla.',
      'Gradually mix in flour mixture.',
      'Fold in chocolate chips.',
      'Drop rounded tablespoons onto baking sheets.',
      'Bake 9-12 minutes until edges are golden.',
      'Cool on sheet 5 minutes before transferring.',
    ],
    tags: ['dessert', 'cookies', 'chocolate', 'baking', 'vegetarian'],
    mealType: ['Dessert', 'Snack'],
  },
  {
    id: 'staple-36',
    name: 'Banana Bread',
    description: 'Moist, flavorful banana bread using overripe bananas.',
    image: 'https://images.unsplash.com/photo-1606101209571-8b5b5f5c5e1b?w=800',
    prepTime: 15,
    cookTime: 60,
    servings: 10,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Dessert',
    ingredients: [
      { item: 'ripe bananas', amount: '3 large, mashed' },
      { item: 'all-purpose flour', amount: '1.5 cups' },
      { item: 'sugar', amount: '3/4 cup' },
      { item: 'butter', amount: '1/3 cup, melted' },
      { item: 'egg', amount: '1' },
      { item: 'baking soda', amount: '1 tsp' },
      { item: 'vanilla extract', amount: '1 tsp' },
      { item: 'salt', amount: '1/4 tsp' },
    ],
    instructions: [
      'Preheat oven to 350°F (175°C). Grease a 9x5 loaf pan.',
      'Mash bananas in a large bowl.',
      'Stir in melted butter, sugar, egg, and vanilla.',
      'Add flour, baking soda, and salt. Mix until just combined.',
      'Pour into prepared pan.',
      'Bake 55-65 minutes until toothpick comes out clean.',
      'Cool in pan 10 minutes, then remove to wire rack.',
    ],
    tags: ['dessert', 'bread', 'banana', 'baking', 'vegetarian'],
    mealType: ['Dessert', 'Breakfast'],
  },
  {
    id: 'staple-37',
    name: 'Brownies',
    description: 'Fudgy, rich chocolate brownies with a crackly top.',
    image: 'https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=800',
    prepTime: 15,
    cookTime: 30,
    servings: 16,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Dessert',
    ingredients: [
      { item: 'butter', amount: '1/2 cup' },
      { item: 'sugar', amount: '1 cup' },
      { item: 'cocoa powder', amount: '1/3 cup' },
      { item: 'eggs', amount: '2' },
      { item: 'vanilla extract', amount: '1 tsp' },
      { item: 'all-purpose flour', amount: '1/2 cup' },
      { item: 'salt', amount: '1/4 tsp' },
      { item: 'chocolate chips', amount: '1/2 cup', optional: true },
    ],
    instructions: [
      'Preheat oven to 350°F (175°C). Grease an 8x8 pan.',
      'Melt butter in a saucepan. Remove from heat.',
      'Stir in sugar and cocoa until smooth.',
      'Beat in eggs one at a time, then vanilla.',
      'Stir in flour and salt until just combined.',
      'Fold in chocolate chips if using.',
      'Spread in prepared pan.',
      'Bake 25-30 minutes. Don\'t overbake.',
      'Cool completely before cutting.',
    ],
    tags: ['dessert', 'brownies', 'chocolate', 'baking', 'vegetarian'],
    mealType: ['Dessert', 'Snack'],
  },
  {
    id: 'staple-38',
    name: 'Apple Pie',
    description: 'Classic American apple pie with flaky crust and cinnamon-spiced filling.',
    image: 'https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=800',
    prepTime: 45,
    cookTime: 55,
    servings: 8,
    difficulty: 'Medium',
    cuisine: 'American',
    category: 'Dessert',
    ingredients: [
      { item: 'pie crusts', amount: '2 (store-bought or homemade)' },
      { item: 'apples', amount: '6-7 cups, peeled and sliced' },
      { item: 'sugar', amount: '3/4 cup' },
      { item: 'cinnamon', amount: '1 tsp' },
      { item: 'nutmeg', amount: '1/4 tsp' },
      { item: 'flour', amount: '2 tbsp' },
      { item: 'lemon juice', amount: '1 tbsp' },
      { item: 'butter', amount: '2 tbsp, cubed' },
    ],
    instructions: [
      'Preheat oven to 425°F (220°C).',
      'Fit one crust into a 9-inch pie dish.',
      'Toss apples with sugar, cinnamon, nutmeg, flour, and lemon juice.',
      'Pour filling into crust. Dot with butter.',
      'Cover with second crust. Crimp edges and cut vents.',
      'Bake 45-55 minutes until golden and bubbly.',
      'Cool at least 2 hours before serving.',
    ],
    tags: ['dessert', 'pie', 'apple', 'baking', 'holiday'],
    mealType: ['Dessert'],
  },
  {
    id: 'staple-39',
    name: 'Vanilla Cupcakes',
    description: 'Light, fluffy vanilla cupcakes with creamy frosting.',
    image: 'https://images.unsplash.com/photo-1519869325930-281384150729?w=800',
    prepTime: 20,
    cookTime: 20,
    servings: 12,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Dessert',
    ingredients: [
      { item: 'all-purpose flour', amount: '1.5 cups' },
      { item: 'sugar', amount: '1 cup' },
      { item: 'butter', amount: '1/2 cup, softened' },
      { item: 'eggs', amount: '2' },
      { item: 'milk', amount: '1/2 cup' },
      { item: 'vanilla extract', amount: '2 tsp' },
      { item: 'baking powder', amount: '1.5 tsp' },
      { item: 'salt', amount: '1/4 tsp' },
    ],
    instructions: [
      'Preheat oven to 350°F (175°C). Line muffin tin with cupcake liners.',
      'Whisk flour, baking powder, and salt. Set aside.',
      'Beat butter and sugar until light and fluffy.',
      'Add eggs one at a time, then vanilla.',
      'Alternate adding flour mixture and milk, mixing until just combined.',
      'Fill liners 2/3 full.',
      'Bake 18-22 minutes until toothpick comes out clean.',
      'Cool completely before frosting.',
    ],
    tags: ['dessert', 'cupcakes', 'vanilla', 'baking', 'birthday'],
    mealType: ['Dessert'],
  },
  {
    id: 'staple-40',
    name: 'Rice Pudding',
    description: 'Creamy, comforting rice pudding with cinnamon.',
    image: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800',
    prepTime: 5,
    cookTime: 40,
    servings: 6,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Dessert',
    ingredients: [
      { item: 'cooked rice', amount: '2 cups' },
      { item: 'milk', amount: '2 cups' },
      { item: 'sugar', amount: '1/3 cup' },
      { item: 'egg', amount: '1, beaten' },
      { item: 'vanilla extract', amount: '1 tsp' },
      { item: 'cinnamon', amount: '1/2 tsp' },
      { item: 'raisins', amount: '1/3 cup', optional: true },
    ],
    instructions: [
      'Combine rice, milk, and sugar in a saucepan.',
      'Cook over medium heat, stirring often, for 20 minutes.',
      'Slowly stir a bit of hot mixture into beaten egg to temper.',
      'Add egg mixture back to pan.',
      'Cook 5 more minutes, stirring constantly.',
      'Remove from heat. Stir in vanilla and raisins.',
      'Serve warm or chilled, sprinkled with cinnamon.',
    ],
    tags: ['dessert', 'pudding', 'rice', 'comfort-food', 'vegetarian'],
    mealType: ['Dessert'],
  },

  // ============ SNACKS & APPETIZERS ============
  {
    id: 'staple-41',
    name: 'Hummus',
    description: 'Creamy homemade hummus with tahini and garlic.',
    image: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=800',
    prepTime: 10,
    cookTime: 0,
    servings: 8,
    difficulty: 'Easy',
    cuisine: 'Mediterranean',
    category: 'Starter',
    ingredients: [
      { item: 'chickpeas', amount: '15 oz can, drained' },
      { item: 'tahini', amount: '1/4 cup' },
      { item: 'lemon juice', amount: '3 tbsp' },
      { item: 'garlic', amount: '2 cloves' },
      { item: 'olive oil', amount: '2 tbsp' },
      { item: 'cumin', amount: '1/2 tsp' },
      { item: 'salt', amount: '1/2 tsp' },
    ],
    instructions: [
      'Add all ingredients to a food processor.',
      'Blend until smooth, about 2 minutes.',
      'Add 2-3 tbsp water if needed for consistency.',
      'Taste and adjust lemon, salt, and garlic.',
      'Transfer to a bowl and drizzle with olive oil.',
      'Serve with pita bread, vegetables, or crackers.',
    ],
    tags: ['appetizer', 'hummus', 'mediterranean', 'vegan', 'healthy'],
    mealType: ['Snack', 'Starter'],
  },
  {
    id: 'staple-42',
    name: 'Guacamole',
    description: 'Fresh, chunky guacamole with lime and cilantro.',
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=800',
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'Mexican',
    category: 'Starter',
    ingredients: [
      { item: 'ripe avocados', amount: '3' },
      { item: 'lime juice', amount: '2 tbsp' },
      { item: 'red onion', amount: '1/4 cup, diced' },
      { item: 'cilantro', amount: '2 tbsp, chopped' },
      { item: 'jalapeño', amount: '1, seeded and minced', optional: true },
      { item: 'salt', amount: '1/2 tsp' },
      { item: 'tomato', amount: '1, diced', optional: true },
    ],
    instructions: [
      'Cut avocados in half and remove pits.',
      'Scoop flesh into a bowl.',
      'Add lime juice and salt, mash to desired consistency.',
      'Fold in onion, cilantro, jalapeño, and tomato.',
      'Taste and adjust seasonings.',
      'Serve immediately with tortilla chips.',
    ],
    tags: ['appetizer', 'guacamole', 'mexican', 'vegan', 'avocado'],
    mealType: ['Snack', 'Starter'],
  },
  {
    id: 'staple-43',
    name: 'Deviled Eggs',
    description: 'Classic deviled eggs with creamy, tangy filling.',
    image: 'https://images.unsplash.com/photo-1522881193457-37ae97c905bf?w=800',
    prepTime: 20,
    cookTime: 12,
    servings: 12,
    difficulty: 'Easy',
    cuisine: 'American',
    category: 'Starter',
    ingredients: [
      { item: 'eggs', amount: '6' },
      { item: 'mayonnaise', amount: '3 tbsp' },
      { item: 'dijon mustard', amount: '1 tsp' },
      { item: 'apple cider vinegar', amount: '1 tsp' },
      { item: 'salt and pepper', amount: 'to taste' },
      { item: 'paprika', amount: 'for garnish' },
    ],
    instructions: [
      'Place eggs in a pot, cover with cold water.',
      'Bring to a boil, then cover and remove from heat.',
      'Let sit 12 minutes, then transfer to ice bath.',
      'Peel eggs and cut in half lengthwise.',
      'Remove yolks to a bowl.',
      'Mash yolks with mayo, mustard, vinegar, salt, and pepper.',
      'Pipe or spoon filling into egg white halves.',
      'Sprinkle with paprika.',
    ],
    tags: ['appetizer', 'eggs', 'party', 'vegetarian'],
    mealType: ['Starter', 'Snack'],
  },
  {
    id: 'staple-44',
    name: 'Bruschetta',
    description: 'Toasted bread topped with fresh tomato, basil, and garlic.',
    image: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=800',
    prepTime: 15,
    cookTime: 5,
    servings: 8,
    difficulty: 'Easy',
    cuisine: 'Italian',
    category: 'Starter',
    ingredients: [
      { item: 'baguette', amount: '1, sliced' },
      { item: 'tomatoes', amount: '4, diced' },
      { item: 'fresh basil', amount: '1/4 cup, chopped' },
      { item: 'garlic', amount: '3 cloves, minced' },
      { item: 'olive oil', amount: '3 tbsp' },
      { item: 'balsamic vinegar', amount: '1 tbsp' },
      { item: 'salt and pepper', amount: 'to taste' },
    ],
    instructions: [
      'Toast baguette slices until golden.',
      'Rub each slice with a cut garlic clove.',
      'Combine tomatoes, basil, remaining garlic, oil, and vinegar.',
      'Season with salt and pepper.',
      'Let mixture sit 15 minutes for flavors to meld.',
      'Spoon tomato mixture onto toasted bread.',
      'Drizzle with extra olive oil and serve.',
    ],
    tags: ['appetizer', 'bruschetta', 'italian', 'tomato', 'vegan'],
    mealType: ['Starter'],
  },
  {
    id: 'staple-45',
    name: 'French Fries',
    description: 'Crispy homemade french fries - better than any restaurant.',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f390859f?w=800',
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    difficulty: 'Medium',
    cuisine: 'American',
    category: 'Side',
    ingredients: [
      { item: 'russet potatoes', amount: '2 lbs' },
      { item: 'vegetable oil', amount: 'for frying' },
      { item: 'salt', amount: 'to taste' },
    ],
    instructions: [
      'Cut potatoes into 1/4-inch sticks.',
      'Soak in cold water for 30 minutes. Drain and dry thoroughly.',
      'Heat oil to 325°F (165°C) in a deep pot.',
      'Fry potatoes in batches for 4-5 minutes. They won\'t be golden yet.',
      'Remove and drain on paper towels.',
      'Increase oil temperature to 375°F (190°C).',
      'Fry again for 2-3 minutes until golden and crispy.',
      'Drain, season with salt, serve immediately.',
    ],
    tags: ['side', 'fries', 'potatoes', 'vegan'],
    mealType: ['Side', 'Snack'],
  },

  // ============ INTERNATIONAL STAPLES ============
  {
    id: 'staple-46',
    name: 'Pad Thai',
    description: 'Sweet, sour, and savory Thai rice noodles with shrimp or chicken.',
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Medium',
    cuisine: 'Thai',
    category: 'Miscellaneous',
    ingredients: [
      { item: 'rice noodles', amount: '8 oz' },
      { item: 'shrimp or chicken', amount: '1 lb' },
      { item: 'eggs', amount: '2' },
      { item: 'fish sauce', amount: '3 tbsp' },
      { item: 'tamarind paste', amount: '2 tbsp' },
      { item: 'brown sugar', amount: '2 tbsp' },
      { item: 'bean sprouts', amount: '1 cup' },
      { item: 'green onions', amount: '3, chopped' },
      { item: 'peanuts', amount: '1/4 cup, crushed' },
      { item: 'lime wedges', amount: 'for serving' },
    ],
    instructions: [
      'Soak rice noodles in warm water for 30 minutes. Drain.',
      'Mix fish sauce, tamarind, and brown sugar for sauce.',
      'Heat oil in a wok over high heat.',
      'Cook shrimp or chicken until done. Remove.',
      'Scramble eggs in the wok, push to the side.',
      'Add noodles and sauce, toss until noodles soften.',
      'Add protein, bean sprouts, and green onions.',
      'Serve with peanuts and lime wedges.',
    ],
    tags: ['dinner', 'thai', 'noodles', 'shrimp', 'asian'],
    mealType: ['Dinner'],
  },
  {
    id: 'staple-47',
    name: 'Fried Chicken',
    description: 'Crispy, juicy Southern-style fried chicken.',
    image: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=800',
    prepTime: 30,
    cookTime: 20,
    servings: 4,
    difficulty: 'Medium',
    cuisine: 'American',
    category: 'Chicken',
    ingredients: [
      { item: 'chicken pieces', amount: '3 lbs' },
      { item: 'buttermilk', amount: '2 cups' },
      { item: 'all-purpose flour', amount: '2 cups' },
      { item: 'paprika', amount: '1 tbsp' },
      { item: 'garlic powder', amount: '1 tsp' },
      { item: 'cayenne pepper', amount: '1/2 tsp' },
      { item: 'salt', amount: '2 tsp' },
      { item: 'vegetable oil', amount: 'for frying' },
    ],
    instructions: [
      'Marinate chicken in buttermilk for at least 2 hours.',
      'Mix flour with paprika, garlic powder, cayenne, and salt.',
      'Heat oil to 350°F (175°C) in a deep pot or fryer.',
      'Remove chicken from buttermilk, let excess drip off.',
      'Dredge in seasoned flour, pressing to coat well.',
      'Fry in batches for 12-15 minutes, turning once.',
      'Internal temperature should reach 165°F.',
      'Drain on wire rack. Rest 5 minutes before serving.',
    ],
    tags: ['dinner', 'chicken', 'fried', 'southern', 'comfort-food'],
    mealType: ['Dinner'],
  },
  {
    id: 'staple-48',
    name: 'Butter Chicken',
    description: 'Creamy, mildly spiced Indian chicken curry in tomato sauce.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800',
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: 'Medium',
    cuisine: 'Indian',
    category: 'Chicken',
    ingredients: [
      { item: 'chicken thighs', amount: '1.5 lbs, cubed' },
      { item: 'butter', amount: '4 tbsp' },
      { item: 'onion', amount: '1, diced' },
      { item: 'garlic', amount: '4 cloves, minced' },
      { item: 'ginger', amount: '1 tbsp, grated' },
      { item: 'tomato puree', amount: '1 cup' },
      { item: 'heavy cream', amount: '1 cup' },
      { item: 'garam masala', amount: '2 tbsp' },
      { item: 'cumin', amount: '1 tsp' },
      { item: 'turmeric', amount: '1/2 tsp' },
    ],
    instructions: [
      'Season chicken with garam masala, cumin, and turmeric.',
      'Melt 2 tbsp butter in a pan, brown chicken. Remove.',
      'Add remaining butter, sauté onion until soft.',
      'Add garlic and ginger, cook 1 minute.',
      'Stir in tomato puree, simmer 10 minutes.',
      'Add cream and return chicken to pan.',
      'Simmer 15 minutes until chicken is cooked through.',
      'Serve over basmati rice with naan bread.',
    ],
    tags: ['dinner', 'indian', 'curry', 'chicken', 'creamy'],
    mealType: ['Dinner'],
  },
  {
    id: 'staple-49',
    name: 'Fish Tacos',
    description: 'Light, flavorful fish tacos with slaw and creamy sauce.',
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800',
    prepTime: 20,
    cookTime: 10,
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'Mexican',
    category: 'Seafood',
    ingredients: [
      { item: 'white fish fillets', amount: '1 lb (cod, tilapia)' },
      { item: 'corn tortillas', amount: '8' },
      { item: 'cabbage', amount: '2 cups, shredded' },
      { item: 'sour cream', amount: '1/2 cup' },
      { item: 'lime juice', amount: '2 tbsp' },
      { item: 'cumin', amount: '1 tsp' },
      { item: 'chili powder', amount: '1 tsp' },
      { item: 'cilantro', amount: '1/4 cup, chopped' },
    ],
    instructions: [
      'Season fish with cumin, chili powder, salt, and pepper.',
      'Pan-fry or grill fish 3-4 minutes per side until flaky.',
      'Mix sour cream with 1 tbsp lime juice for crema.',
      'Toss cabbage with remaining lime juice and cilantro.',
      'Warm tortillas in a dry pan.',
      'Break fish into chunks and divide among tortillas.',
      'Top with slaw and drizzle with crema.',
      'Serve with lime wedges.',
    ],
    tags: ['dinner', 'mexican', 'fish', 'tacos', 'healthy'],
    mealType: ['Dinner'],
  },
  {
    id: 'staple-50',
    name: 'Ramen',
    description: 'Quick homemade ramen with soft-boiled egg and toppings.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800',
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: 'Easy',
    cuisine: 'Japanese',
    category: 'Soup',
    ingredients: [
      { item: 'ramen noodles', amount: '2 packages' },
      { item: 'chicken broth', amount: '4 cups' },
      { item: 'soy sauce', amount: '2 tbsp' },
      { item: 'mirin', amount: '1 tbsp' },
      { item: 'eggs', amount: '2' },
      { item: 'green onions', amount: '2, sliced' },
      { item: 'sesame oil', amount: '1 tsp' },
      { item: 'nori sheets', amount: '2', optional: true },
    ],
    instructions: [
      'Soft boil eggs: cook 7 minutes, then ice bath. Peel and halve.',
      'Bring broth to simmer with soy sauce, mirin, and sesame oil.',
      'Cook noodles according to package, drain.',
      'Divide noodles between two bowls.',
      'Ladle hot broth over noodles.',
      'Top with soft-boiled egg halves, green onions, and nori.',
      'Add any additional toppings: corn, mushrooms, pork.',
    ],
    tags: ['dinner', 'japanese', 'ramen', 'soup', 'noodles'],
    mealType: ['Dinner', 'Lunch'],
  },
];
